import { texts } from './texts';
const imgPath = 'images/containers/';

export const containers = [
    {
        title: "Pallet Wide 40' PW container.",
        description:
            'This is a new type of container of increased capacity in international practice, which can hold 30 euro pallets on the floor. This capacity is achieved by increasing the width of the container (reducing the depth of the ribs).',
        outer: {
            length: '12,192',
            width: '2,484',
            height: '2,896',
        },
        inner: {
            length: '12,100',
            width: '2,426',
            height: '2,694',
        },
        doors: {
            width: '2,360 mm',
            height: '2,585 mm',
        },
        maxGrossWeight: '34 000 kg',
        tare: '4,150 kg',
        maxLoad: '29,850 kg',
        volume: '79.1 cub. M>',
        img: imgPath + 'container1.png',
    },
    {
        title: "20' Pallet Wide \n(20' HC PW, increased capacity)",
        description:
            'Used when transporting small oversized loads or medium quantities of small oversized loads',
        outer: {
            length: '6,058',
            width: '2,484',
            height: '2,896',
        },
        inner: {
            length: '5,898',
            width: '2,440',
            height: '2,698',
        },
        doors: {
            width: '2,374 mm',
            height: '2,585 mm',
        },
        maxGrossWeight: '30 480 kg',
        tare: '2,560 kg',
        maxLoad: '27,920 kg',
        volume: '38.4 cub. M>',
        img: imgPath + 'container2.png',
        className: 'shrink-img',
    },
    {
        title: '20-foot reinforced container \n(HEAVY TESTED)',
        description:
            'For the transportation of heavy loads (porcelain stoneware, natural stone, metal products)',
        outer: {
            length: '6,058',
            width: '2,438',
            height: '2,591',
        },
        inner: {
            length: '5,898',
            width: '2,352',
            height: '2,393',
        },
        doors: {
            width: '2,340 mm',
            height: '2,280 mm',
        },
        maxGrossWeight: '30 500 kg',
        tare: '2,300 kg',
        maxLoad: '28,200 kg',
        volume: '33.10 cub. M>',
        img: imgPath + 'container2.png',
        className: 'shrink-img',
    },
    {
        title: '45-foot standard container',
        description:
            "The 45' standard container is used for light and bulky goods and is also ideal for transporting loads of exactly 12 meters or more up to 13.5 meters in length.",
        outer: {
            length: '13,742',
            width: '2,438',
            height: '2,895',
        },
        inner: {
            length: '13,582',
            width: '2,347',
            height: '2,690',
        },
        doors: {
            width: '2,340 mm',
            height: '2,584 mm',
        },
        maxGrossWeight: '32 500 kg',
        tare: '4,110 kg',
        maxLoad: '28,390 kg',
        volume: '85.7 cub. M>',
        img: imgPath + 'container4.png',
    },
    {
        title: "40-foot High Cube (40' HC) container \n(increased capacity)",
        description: texts.containerSharedDescription,
        outer: {
            length: '12,192',
            width: '2,438',
            height: '2,896',
        },
        inner: {
            length: '12,032',
            width: '2,352',
            height: '2,698',
        },
        doors: {
            width: '2,340 mm',
            height: '2,585 mm',
        },
        maxGrossWeight: '32 500 kg',
        tare: '3,850 kg',
        maxLoad: '28,650 kg',
        volume: '76.4 cub. M>',
        img: imgPath + 'container1.png',
    },
    {
        title: "20' High Cube container{n}.",
        description: texts.containerSharedDescription,
        outer: {
            length: '6,058',
            width: '2,484',
            height: '2,896',
        },
        inner: {
            length: '5,898',
            width: '2,440',
            height: '2,698',
        },
        doors: {
            width: '2,374 mm',
            height: '2,585 mm',
        },
        maxGrossWeight: '30 480 kg',
        tare: '2,560 kg',
        maxLoad: '27,920 kg',
        volume: '38.4 cub. M>',
        img: imgPath + 'container2.png',
        className: 'shrink-img',
    },
    {
        title: '40-foot standard (steel) container',
        description: texts.containerSharedDescription2,
        outer: {
            length: '12,192',
            width: '2,438',
            height: '2,591',
        },
        inner: {
            length: '12,039',
            width: '2,350',
            height: '2,372',
        },
        doors: {
            width: '2,336 mm',
            height: '2,291 mm',
        },
        maxGrossWeight: '30 480 kg',
        tare: '3,980 kg',
        maxLoad: '26,500 kg',
        volume: '66.5 cub. M>',
        img: imgPath + 'container4.png',
    },
    {
        title: '20-foot standard (steel) container',
        description: texts.containerSharedDescription2,
        outer: {
            length: '6,058',
            width: '2,438',
            height: '2,591',
        },
        inner: {
            length: '5,898',
            width: '2,352',
            height: '2,393',
        },
        doors: {
            width: '2,340 mm',
            height: '2,280 mm',
        },
        maxGrossWeight: '30 480 kg',
        tare: '2,220 kg',
        maxLoad: '28,260 kg',
        volume: '33.2 cub. M>',
        img: imgPath + 'container2.png',
        className: 'shrink-img',
    },
    {
        title: '20-foot (steel) open top container \nOPEN TOP',
        description: texts.containerSharedDescription3,
        outer: {
            length: '6,096',
            width: '2,438',
            height: '2,591',
        },
        inner: {
            length: '5,902',
            width: '2,240',
            height: '2,352',
        },
        doors: {
            width: '2,335 mm',
            height: '2,240 mm',
        },
        maxGrossWeight: '24 000 kg',
        tare: '2,440 kg',
        maxLoad: '21,560 kg',
        volume: '32 cub. M>',
        img: imgPath + 'container9.png',
        className: 'shrink-img-open',
    },
    {
        title: '40-foot (steel) open top container',
        description: texts.containerSharedDescription3,
        outer: {
            length: '12,192',
            width: '2,438',
            height: '2,591',
        },
        inner: {
            length: '12,021',
            width: '2,350',
            height: '2,330',
        },
        doors: {
            width: '2,338 mm',
            height: '2,234 mm',
        },
        maxGrossWeight: '36 000 kg',
        tare: '4,430 kg',
        maxLoad: '31,570 kg',
        volume: '66.7 cub. M>',
        img: imgPath + 'container10.png',
        className: 'grow-img',
    },
    {
        title: '40-foot (steel) Hard Top container with removable rigid lid',
        description:
            'For ease of loading, the container shall be equipped with a removable top bar over the doors at the end of the container.',
        outer: {
            length: '12,192',
            width: '2,438',
            height: '2,591',
        },
        inner: {
            length: '12,021',
            width: '2,350',
            height: '2,330',
        },
        doors: {
            width: '2,338 mm',
            height: '2,234 mm',
        },
        maxGrossWeight: '36 000 kg',
        tare: '4,430 kg',
        maxLoad: '31,570 kg',
        volume: '66.7 cub. M>',
        img: imgPath + 'container11.png',
        className: 'grow-img',
    },
    {
        title: '20-foot (steel) container with end walls',
        description: texts.containerSharedDescription4,
        outer: {
            length: '6,096',
            width: '2,438',
            height: '2,591',
        },
        inner: {
            length: '5,737',
            width: '2,240',
            height: '2,170 mm\n420 mm\n (compact)',
        },
        doors: {
            width: '--',
            height: '--',
        },
        maxGrossWeight: '30 480 kg',
        tare: '2,950 kg',
        maxLoad: '27,530 kg',
        volume: '27.9 cub. M>',
        img: imgPath + 'container12.png',
        className: 'grow-img stretch-row',
    },
    {
        title: '40-foot (steel) container with end walls',
        description: texts.containerSharedDescription4,
        outer: {
            length: '12,192',
            width: '2,438',
            height: '2,591',
        },
        inner: {
            length: '12,032',
            width: '2,240',
            height: '2,034 mm\n570 mm\n (compact)',
        },
        doors: {
            width: '--',
            height: '--',
        },
        maxGrossWeight: '45 000 kg',
        tare: '5,530 kg',
        maxLoad: '39,470 kg',
        volume: '58.8 cub. M>',
        img: imgPath + 'container13.png',
        className: 'grow-img stretch-row',
    },
    {
        title: '40-foot High Cube refrigerated (steel) container (increased capacity)',
        description: texts.containerSharedDescription,
        outer: {
            length: '12,192',
            width: '2,438',
            height: '2,895',
        },
        inner: {
            length: '11,560',
            width: '2,286',
            height: '2,500',
        },
        doors: {
            width: '2,286 mm',
            height: '2,478 mm',
        },
        maxGrossWeight: '30 480 kg',
        tare: '4,200 kg',
        maxLoad: '26,280 kg',
        volume: '66.1 cub. M>',
        img: imgPath + 'container1.png',
    },
    {
        title: '40-foot refrigerated \n(steel) container',
        description: texts.containerSharedDescription,
        outer: {
            length: '12,192',
            width: '2,438',
            height: '2,591',
        },
        inner: {
            length: '11,555',
            width: '2,286',
            height: '2,280',
        },
        doors: {
            width: '2,286 mm',
            height: '2,245 mm',
        },
        maxGrossWeight: '30 480 kg',
        tare: '4,370 kg',
        maxLoad: '26,110 kg',
        volume: '60.2 cub. M>',
        img: imgPath + 'container4.png',
    },
    {
        title: '20-foot refrigerated \n(steel) container',
        description: texts.containerSharedDescription,
        outer: {
            length: '6,096',
            width: '2,370',
            height: '2,591',
        },
        inner: {
            length: '5,455',
            width: '2,260',
            height: '2,275',
        },
        doors: {
            width: '2,340 mm',
            height: '2,260 mm',
        },
        maxGrossWeight: '27,000 kg',
        tare: '3,050 kg',
        maxLoad: '23,950 kg',
        volume: '28.0 cub. M>',
        img: imgPath + 'container2.png',
        className: 'shrink-img',
    },
];

export const containersRus = {
    sizesDesignation: {
        3: '3 t',
        5: '5 t',
        20: '20 t',
        24: '24 t',
    },
    grossWeightTonns: {
        3: '3,0',
        5: '5,0',
        20: '20,0',
        24: '24,0',
    },
    innerVolume: {
        3: '5,16',
        5: '10,40',
        20: '30,60',
        24: '32,70',
    },
    sizes: {
        outer: {
            length: {
                3: '2 100',
                5: '2 650',
                20: '6 058',
                24: '6 058',
            },
            width: {
                3: '1 325',
                5: '2 100',
                20: '2 438',
                24: '2 438',
            },
            height: {
                3: '2 400',
                5: '2 400',
                20: '2 438',
                24: '2 591',
            },
        },
        inner: {
            length: {
                3: '1 930',
                5: '2 515',
                20: '5 867',
                24: '5 867',
            },
            width: {
                3: '1 225',
                5: '1 950',
                20: '2 330',
                24: '2 330',
            },
            height: {
                3: '2 128',
                5: '2 128',
                20: '2 197',
                24: '2 350',
            },
        },
        doors: {
            width: {
                3: '1 225',
                5: '1 950',
                20: '2 286',
                24: '2 286',
            },
            height: {
                3: '2 090',
                5: '2 100',
                20: '2 134',
                24: '2 261',
            },
        },
    },
};
