export const countryCodes = [
    {
        code: 'RU',
        name: 'Россия',
        cn: '俄罗斯',
        phone_code: '+7',
    },
    {
        code: 'CN',
        name: 'China (中国)',
        cn: '',
        phone_code: '+86',
    },
    {
        code: 'AL',
        name: 'Albania',
        cn: '阿尔巴尼亚',
        phone_code: '+355',
    },
    {
        code: 'DZ',
        name: 'Algeria',
        cn: '阿尔及利亚',
        phone_code: '+213',
    },
    {
        code: 'AF',
        name: 'Afghanistan',
        cn: '阿富汗',
        phone_code: '+93',
    },
    {
        code: 'AR',
        name: 'Argentina',
        cn: '阿根廷',
        phone_code: '+54',
    },
    {
        code: 'AE',
        name: 'United Arab Emirates',
        cn: '阿联酋',
        phone_code: '+971',
    },
    {
        code: 'AW',
        name: 'Aruba',
        cn: '阿鲁巴',
        phone_code: '+297',
    },
    {
        code: 'OM',
        name: 'Oman',
        cn: '阿曼',
        phone_code: '+968',
    },
    {
        code: 'AZ',
        name: 'Azerbaijan',
        cn: '阿塞拜疆',
        phone_code: '+994',
    },
    {
        code: 'EG',
        name: 'Egypt',
        cn: '埃及',
        phone_code: '+20',
    },
    {
        code: 'ET',
        name: 'Ethiopia',
        cn: '埃塞俄比亚',
        phone_code: '+251',
    },
    {
        code: 'IE',
        name: 'Ireland',
        cn: '爱尔兰',
        phone_code: '+353',
    },
    {
        code: 'EE',
        name: 'Estonia',
        cn: '爱沙尼亚',
        phone_code: '+372',
    },
    {
        code: 'AD',
        name: 'Andorra',
        cn: '安道尔',
        phone_code: '+376',
    },
    {
        code: 'AO',
        name: 'Angola',
        cn: '安哥拉',
        phone_code: '+244',
    },
    {
        code: 'AI',
        name: 'Anguilla',
        cn: '安圭拉',
        phone_code: '+1264',
    },
    {
        code: 'AG',
        name: 'Antigua',
        cn: '安提瓜岛',
        phone_code: '+1268',
    },
    {
        code: 'AT',
        name: 'Austria',
        cn: '奥地利',
        phone_code: '+43',
    },
    {
        code: 'AU',
        name: 'Australia',
        cn: '澳大利亚',
        phone_code: '+61',
    },
    {
        code: 'MO',
        name: 'Macau',
        cn: '中国澳门特别行政区',
        phone_code: '+853',
    },
    {
        code: 'BB',
        name: 'Barbados',
        cn: '巴巴多斯',
        phone_code: '+1246',
    },
    {
        code: 'PG',
        name: 'Papua New Guinea',
        cn: '巴布亚新几内亚',
        phone_code: '+675',
    },
    {
        code: 'BS',
        name: 'The Bahamas',
        cn: '巴哈马',
        phone_code: '+1242',
    },
    {
        code: 'PK',
        name: 'Pakistan',
        cn: '巴基斯坦',
        phone_code: '+92',
    },
    {
        code: 'PY',
        name: 'Paraguay',
        cn: '巴拉圭',
        phone_code: '+595',
    },
    {
        code: 'PS',
        name: 'Palestine',
        cn: '巴勒斯坦',
        phone_code: '+970',
    },
    {
        code: 'BH',
        name: 'Bahrain',
        cn: '巴林',
        phone_code: '+973',
    },
    {
        code: 'PA',
        name: 'Panama',
        cn: '巴拿马',
        phone_code: '+507',
    },
    {
        code: 'BR',
        name: 'Brazil',
        cn: '巴西',
        phone_code: '+55',
    },
    {
        code: 'BY',
        name: 'Belarus',
        cn: '白俄罗斯',
        phone_code: '+375',
    },
    {
        code: 'BM',
        name: 'Bermuda',
        cn: '百慕大',
        phone_code: '+1441',
    },
    {
        code: 'BG',
        name: 'Bulgaria',
        cn: '保加利亚',
        phone_code: '+359',
    },
    {
        code: 'MP',
        name: 'Northern Mariana Islands',
        cn: '北马里亚纳群岛',
        phone_code: '+1670',
    },
    {
        code: 'BJ',
        name: 'Benin',
        cn: '贝宁',
        phone_code: '+229',
    },
    {
        code: 'BE',
        name: 'Belgium',
        cn: '比利时',
        phone_code: '+32',
    },
    {
        code: 'IS',
        name: 'Iceland',
        cn: '冰岛',
        phone_code: '+354',
    },
    {
        code: 'PR',
        name: 'Puerto Rico',
        cn: '波多黎各',
        phone_code: '+1',
    },
    {
        code: 'PL',
        name: 'Poland',
        cn: '波兰',
        phone_code: '+48',
    },
    {
        code: 'BA',
        name: 'Bosnia and Herzegovina',
        cn: '波斯尼亚和黑塞哥维那',
        phone_code: '+387',
    },
    {
        code: 'BO',
        name: 'Bolivia',
        cn: '玻利维亚',
        phone_code: '+591',
    },
    {
        code: 'BZ',
        name: 'Belize',
        cn: '伯利兹',
        phone_code: '+501',
    },
    {
        code: 'PW',
        name: 'Palau',
        cn: '帛琉',
        phone_code: '+680',
    },
    {
        code: 'BW',
        name: 'Botswana',
        cn: '博茨瓦纳',
        phone_code: '+267',
    },
    {
        code: 'BT',
        name: 'Bhutan',
        cn: '不丹',
        phone_code: '+975',
    },
    {
        code: 'BF',
        name: 'Burkina Faso',
        cn: '布基纳法索',
        phone_code: '+226',
    },
    {
        code: 'BI',
        name: 'Burundi',
        cn: '布隆迪',
        phone_code: '+257',
    },
    {
        code: 'KP',
        name: 'North Korea',
        cn: '朝鲜',
        phone_code: '+850',
    },
    {
        code: 'GQ',
        name: 'Equatorial Guinea',
        cn: '赤道几内亚',
        phone_code: '+240',
    },
    {
        code: 'DK',
        name: 'Denmark',
        cn: '丹麦',
        phone_code: '+45',
    },
    {
        code: 'DE',
        name: 'Germany',
        cn: '德国',
        phone_code: '+49',
    },
    {
        code: 'TL',
        name: 'Timor-Leste',
        cn: '东帝汶',
        phone_code: '+670',
    },
    {
        code: 'TG',
        name: 'Togo',
        cn: '多哥',
        phone_code: '+228',
    },
    {
        code: 'DM',
        name: 'Dominica',
        cn: '多米尼加',
        phone_code: '+1767',
    },
    {
        code: 'DO',
        name: 'Dominican Republic',
        cn: '多米尼加共和国',
        phone_code: '+1809',
    },
    {
        code: 'EC',
        name: 'Ecuador',
        cn: '厄瓜多尔',
        phone_code: '+593',
    },
    {
        code: 'ER',
        name: 'Eritrea',
        cn: '厄立特里亚',
        phone_code: '+291',
    },
    {
        code: 'FR',
        name: 'France',
        cn: '法国',
        phone_code: '+33',
    },
    {
        code: 'FO',
        name: 'Faroe Islands',
        cn: '法罗群岛',
        phone_code: '+298',
    },
    {
        code: 'PF',
        name: 'French Polynesia',
        cn: '法属波利尼西亚',
        phone_code: '+689',
    },
    {
        code: 'GF',
        name: 'French Guiana',
        cn: '法属圭亚那',
        phone_code: '+594',
    },
    {
        code: 'PM',
        name: 'Saint Pierre and Miquelon',
        cn: '法属圣皮埃尔和密克隆岛',
        phone_code: '+508',
    },
    {
        code: 'VA',
        name: 'Vatican City',
        cn: '梵蒂冈城',
        phone_code: '+39',
    },
    {
        code: 'PH',
        name: 'Philippines',
        cn: '菲律宾',
        phone_code: '+63',
    },
    {
        code: 'FJ',
        name: 'Fiji',
        cn: '斐济',
        phone_code: '+679',
    },
    {
        code: 'FI',
        name: 'Finland',
        cn: '芬兰',
        phone_code: '+358',
    },
    {
        code: 'CV',
        name: 'Cape Verde',
        cn: '佛得角',
        phone_code: '+238',
    },
    {
        code: 'FK',
        name: 'Falkland Islands',
        cn: '福克兰群岛',
        phone_code: '+500',
    },
    {
        code: 'GM',
        name: 'The Gambia',
        cn: '冈比亚',
        phone_code: '+220',
    },
    {
        code: 'CG',
        name: 'Republic of the Congo',
        cn: '刚果共和国',
        phone_code: '+242',
    },
    {
        code: 'CD',
        name: 'Democratic Republic of the Congo',
        cn: '刚果民主共和国',
        phone_code: '+243',
    },
    {
        code: 'CO',
        name: 'Colombia',
        cn: '哥伦比亚',
        phone_code: '+57',
    },
    {
        code: 'CR',
        name: 'Costa Rica',
        cn: '哥斯达黎加',
        phone_code: '+506',
    },
    {
        code: 'GD',
        name: 'Grenada',
        cn: '格林纳达岛',
        phone_code: '+1473',
    },
    {
        code: 'GL',
        name: 'Greenland',
        cn: '格陵兰',
        phone_code: '+299',
    },
    {
        code: 'GE',
        name: 'Georgia',
        cn: '格鲁吉亚',
        phone_code: '+995',
    },
    {
        code: 'GG',
        name: 'Guernsey',
        cn: '根西岛',
        phone_code: '+44',
    },
    {
        code: 'CU',
        name: 'Cuba',
        cn: '古巴',
        phone_code: '+53',
    },
    {
        code: 'GP',
        name: 'Guadeloupe',
        cn: '瓜德罗普岛',
        phone_code: '+590',
    },
    {
        code: 'GU',
        name: 'Guam',
        cn: '关岛',
        phone_code: '+1671',
    },
    {
        code: 'GY',
        name: 'Guyana',
        cn: '圭亚那',
        phone_code: '+592',
    },
    {
        code: 'KZ',
        name: 'Kazakhstan',
        cn: '哈萨克斯坦',
        phone_code: '+7',
    },
    {
        code: 'HT',
        name: 'Haiti',
        cn: '海地',
        phone_code: '+509',
    },
    {
        code: 'KR',
        name: 'South Korea',
        cn: '韩国',
        phone_code: '+82',
    },
    {
        code: 'NL',
        name: 'Netherlands',
        cn: '荷兰',
        phone_code: '+31',
    },
    {
        code: 'BQ',
        name: 'Bonaire, Sint Eustatius and Saba',
        cn: '荷兰加勒比区',
        phone_code: '+599',
    },
    {
        code: 'ME',
        name: 'Montenegro',
        cn: '黑山共和国',
        phone_code: '+382',
    },
    {
        code: 'HN',
        name: 'Honduras',
        cn: '洪都拉斯',
        phone_code: '+504',
    },
    {
        code: 'KI',
        name: 'Kiribati',
        cn: '基里巴斯',
        phone_code: '+686',
    },
    {
        code: 'DJ',
        name: 'Djibouti',
        cn: '吉布提',
        phone_code: '+253',
    },
    {
        code: 'KG',
        name: 'Kyrgyzstan',
        cn: '吉尔吉斯斯坦',
        phone_code: '+996',
    },
    {
        code: 'GN',
        name: 'Guinea',
        cn: '几内亚',
        phone_code: '+224',
    },
    {
        code: 'GW',
        name: 'Guinea-Bissau',
        cn: '几内亚比绍共和国',
        phone_code: '+245',
    },
    {
        code: 'CA',
        name: 'Canada',
        cn: '加拿大',
        phone_code: '+1',
    },
    {
        code: 'GH',
        name: 'Ghana',
        cn: '加纳',
        phone_code: '+233',
    },
    {
        code: 'GA',
        name: 'Gabon',
        cn: '加蓬共和国',
        phone_code: '+241',
    },
    {
        code: 'KH',
        name: 'Cambodia',
        cn: '柬埔寨',
        phone_code: '+855',
    },
    {
        code: 'CZ',
        name: 'Czech Republic',
        cn: '捷克',
        phone_code: '+420',
    },
    {
        code: 'ZW',
        name: 'Zimbabwe',
        cn: '津巴布韦',
        phone_code: '+263',
    },
    {
        code: 'CM',
        name: 'Cameroon',
        cn: '喀麦隆',
        phone_code: '+237',
    },
    {
        code: 'QA',
        name: 'Qatar',
        cn: '卡塔尔',
        phone_code: '+974',
    },
    {
        code: 'KY',
        name: 'Cayman Islands',
        cn: '开曼群岛',
        phone_code: '+1345',
    },
    {
        code: 'KM',
        name: 'Comoros',
        cn: '科摩罗',
        phone_code: '+269',
    },
    {
        code: 'XK',
        name: 'Kosovo',
        cn: '科索沃',
        phone_code: '+381',
    },
    {
        code: 'CI',
        name: "Côte d'Ivoire",
        cn: '科特迪瓦',
        phone_code: '+225',
    },
    {
        code: 'KW',
        name: 'Kuwait',
        cn: '科威特',
        phone_code: '+965',
    },
    {
        code: 'HR',
        name: 'Croatia',
        cn: '克罗地亚',
        phone_code: '+385',
    },
    {
        code: 'KE',
        name: 'Kenya',
        cn: '肯尼亚',
        phone_code: '+254',
    },
    {
        code: 'CK',
        name: 'Cook Islands',
        cn: '库克群岛',
        phone_code: '+682',
    },
    {
        code: 'CW',
        name: 'Curaçao',
        cn: '库拉索',
        phone_code: '+599',
    },
    {
        code: 'LV',
        name: 'Latvia',
        cn: '拉脱维亚',
        phone_code: '+371',
    },
    {
        code: 'LS',
        name: 'Lesotho',
        cn: '莱索托',
        phone_code: '+266',
    },
    {
        code: 'LA',
        name: 'Laos',
        cn: '老挝',
        phone_code: '+856',
    },
    {
        code: 'LB',
        name: 'Lebanon',
        cn: '黎巴嫩',
        phone_code: '+961',
    },
    {
        code: 'LT',
        name: 'Lithuania',
        cn: '立陶宛',
        phone_code: '+370',
    },
    {
        code: 'LR',
        name: 'Liberia',
        cn: '利比里亚',
        phone_code: '+231',
    },
    {
        code: 'LY',
        name: 'Libya',
        cn: '利比亞',
        phone_code: '+218',
    },
    {
        code: 'LI',
        name: 'Liechtenstein',
        cn: '列支敦士登',
        phone_code: '+423',
    },
    {
        code: 'RE',
        name: 'Réunion',
        cn: '留尼汪',
        phone_code: '+262',
    },
    {
        code: 'LU',
        name: 'Luxembourg',
        cn: '卢森堡',
        phone_code: '+352',
    },
    {
        code: 'RW',
        name: 'Rwanda',
        cn: '卢旺达',
        phone_code: '+250',
    },
    {
        code: 'RO',
        name: 'Romania',
        cn: '罗马尼亚',
        phone_code: '+40',
    },
    {
        code: 'MG',
        name: 'Madagascar',
        cn: '马达加斯加',
        phone_code: '+261',
    },
    {
        code: 'IM',
        name: 'Isle Of Man',
        cn: '马恩岛',
        phone_code: '+44',
    },
    {
        code: 'MV',
        name: 'Maldives',
        cn: '马尔代夫',
        phone_code: '+960',
    },
    {
        code: 'MT',
        name: 'Malta',
        cn: '马耳他',
        phone_code: '+356',
    },
    {
        code: 'MW',
        name: 'Malawi',
        cn: '马拉维',
        phone_code: '+265',
    },
    {
        code: 'MY',
        name: 'Malaysia',
        cn: '马来西亚',
        phone_code: '+60',
    },
    {
        code: 'ML',
        name: 'Mali',
        cn: '马里',
        phone_code: '+223',
    },
    {
        code: 'MK',
        name: 'Macedonia',
        cn: '马其顿',
        phone_code: '+389',
    },
    {
        code: 'MH',
        name: 'Marshall Islands',
        cn: '马绍尔群岛',
        phone_code: '+692',
    },
    {
        code: 'MQ',
        name: 'Martinique',
        cn: '马提尼克',
        phone_code: '+596',
    },
    {
        code: 'YT',
        name: 'Mayotte',
        cn: '马约特',
        phone_code: '+262',
    },
    {
        code: 'MU',
        name: 'Mauritius',
        cn: '毛里求斯',
        phone_code: '+230',
    },
    {
        code: 'MR',
        name: 'Mauritania',
        cn: '毛里塔尼亚',
        phone_code: '+222',
    },
    {
        code: 'US',
        name: 'United States',
        cn: '美国',
        phone_code: '+1',
    },
    {
        code: 'AS',
        name: 'American Samoa',
        cn: '美属萨摩亚',
        phone_code: '+1684',
    },
    {
        code: 'VI',
        name: 'US Virgin Islands',
        cn: '美属维京群岛',
        phone_code: '+1340',
    },
    {
        code: 'MN',
        name: 'Mongolia',
        cn: '蒙古',
        phone_code: '+976',
    },
    {
        code: 'MS',
        name: 'Montserrat',
        cn: '蒙特塞拉特',
        phone_code: '+1664',
    },
    {
        code: 'BD',
        name: 'Bangladesh',
        cn: '孟加拉国',
        phone_code: '+880',
    },
    {
        code: 'PE',
        name: 'Peru',
        cn: '秘鲁',
        phone_code: '+51',
    },
    {
        code: 'FM',
        name: 'Federated States of Micronesia',
        cn: '密克罗尼西亚联邦',
        phone_code: '+691',
    },
    {
        code: 'MM',
        name: 'Myanmar',
        cn: '缅甸',
        phone_code: '+95',
    },
    {
        code: 'MD',
        name: 'Moldova',
        cn: '摩尔多瓦',
        phone_code: '+373',
    },
    {
        code: 'MA',
        name: 'Morocco',
        cn: '摩洛哥',
        phone_code: '+212',
    },
    {
        code: 'MC',
        name: 'Monaco',
        cn: '摩纳哥',
        phone_code: '+377',
    },
    {
        code: 'MZ',
        name: 'Mozambique',
        cn: '莫桑比克',
        phone_code: '+258',
    },
    {
        code: 'MX',
        name: 'Mexico',
        cn: '墨西哥',
        phone_code: '+52',
    },
    {
        code: 'NA',
        name: 'Namibia',
        cn: '纳米比亚',
        phone_code: '+264',
    },
    {
        code: 'ZA',
        name: 'South Africa',
        cn: '南非',
        phone_code: '+27',
    },
    {
        code: 'SS',
        name: 'South Sudan',
        cn: '南苏丹',
        phone_code: '+211',
    },
    {
        code: 'NR',
        name: 'Nauru',
        cn: '瑙鲁',
        phone_code: '+674',
    },
    {
        code: 'NI',
        name: 'Nicaragua',
        cn: '尼加拉瓜',
        phone_code: '+505',
    },
    {
        code: 'NP',
        name: 'Nepal',
        cn: '尼泊尔',
        phone_code: '+977',
    },
    {
        code: 'NE',
        name: 'Niger',
        cn: '尼日尔',
        phone_code: '+227',
    },
    {
        code: 'NG',
        name: 'Nigeria',
        cn: '尼日利亚',
        phone_code: '+234',
    },
    {
        code: 'NU',
        name: 'Niue',
        cn: '纽埃',
        phone_code: '+683',
    },
    {
        code: 'NO',
        name: 'Norway',
        cn: '挪威',
        phone_code: '+47',
    },
    {
        code: 'NF',
        name: 'Norfolk Island',
        cn: '诺福克群岛',
        phone_code: '+672',
    },
    {
        code: 'PT',
        name: 'Portugal',
        cn: '葡萄牙',
        phone_code: '+351',
    },
    {
        code: 'JP',
        name: 'Japan',
        cn: '日本',
        phone_code: '+81',
    },
    {
        code: 'SE',
        name: 'Sweden',
        cn: '瑞典',
        phone_code: '+46',
    },
    {
        code: 'CH',
        name: 'Switzerland',
        cn: '瑞士',
        phone_code: '+41',
    },
    {
        code: 'SV',
        name: 'El Salvador',
        cn: '萨尔瓦多',
        phone_code: '+503',
    },
    {
        code: 'WS',
        name: 'Samoa',
        cn: '萨摩亚',
        phone_code: '+685',
    },
    {
        code: 'RS',
        name: 'Serbia',
        cn: '塞尔维亚',
        phone_code: '+381',
    },
    {
        code: 'SL',
        name: 'Sierra Leone',
        cn: '塞拉利昂',
        phone_code: '+232',
    },
    {
        code: 'SN',
        name: 'Senegal',
        cn: '塞内加尔',
        phone_code: '+221',
    },
    {
        code: 'CY',
        name: 'Cyprus',
        cn: '塞浦路斯',
        phone_code: '+357',
    },
    {
        code: 'SC',
        name: 'Seychelles',
        cn: '塞舌尔',
        phone_code: '+248',
    },
    {
        code: 'SA',
        name: 'Saudi Arabia',
        cn: '沙特阿拉伯',
        phone_code: '+966',
    },
    {
        code: 'BL',
        name: 'Saint Barthélemy',
        cn: '圣巴泰勒米',
        phone_code: '+590',
    },
    {
        code: 'ST',
        name: 'Sao Tome and Principe',
        cn: '圣多美和普林西比民主共和国',
        phone_code: '+239',
    },
    {
        code: 'SH',
        name: 'Saint Helena',
        cn: '圣赫勒拿',
        phone_code: '+290',
    },
    {
        code: 'KN',
        name: 'Saint Kitts and Nevis',
        cn: '圣基茨和尼维斯',
        phone_code: '+1869',
    },
    {
        code: 'LC',
        name: 'Saint Lucia',
        cn: '圣卢西亚',
        phone_code: '+1758',
    },
    {
        code: 'MF',
        name: 'Saint Martin',
        cn: '法属圣马丁',
        phone_code: '+590',
    },
    {
        code: 'SX',
        name: 'Sint Maarten',
        cn: '荷属圣马丁',
        phone_code: '+599',
    },
    {
        code: 'SM',
        name: 'San Marino',
        cn: '圣马力诺',
        phone_code: '+378',
    },
    {
        code: 'VC',
        name: 'Saint Vincent and the Grenadines',
        cn: '圣文森特和格林纳丁斯',
        phone_code: '+1784',
    },
    {
        code: 'LK',
        name: 'Sri Lanka',
        cn: '斯里兰卡',
        phone_code: '+94',
    },
    {
        code: 'SK',
        name: 'Slovakia',
        cn: '斯洛伐克',
        phone_code: '+421',
    },
    {
        code: 'SI',
        name: 'Slovenia',
        cn: '斯洛文尼亚',
        phone_code: '+386',
    },
    {
        code: 'SZ',
        name: 'Swaziland',
        cn: '斯威士兰',
        phone_code: '+268',
    },
    {
        code: 'SD',
        name: 'Sudan',
        cn: '苏丹',
        phone_code: '+249',
    },
    {
        code: 'SR',
        name: 'Suriname',
        cn: '苏里南',
        phone_code: '+597',
    },
    {
        code: 'SB',
        name: 'Solomon Islands',
        cn: '所罗门群岛',
        phone_code: '+677',
    },
    {
        code: 'SO',
        name: 'Somalia',
        cn: '索马里',
        phone_code: '+252',
    },
    {
        code: 'TJ',
        name: 'Tajikistan',
        cn: '塔吉克斯坦',
        phone_code: '+992',
    },
    {
        code: 'TW',
        name: 'Taiwan',
        cn: '台湾',
        phone_code: '+886',
    },
    {
        code: 'TH',
        name: 'Thailand',
        cn: '泰国',
        phone_code: '+66',
    },
    {
        code: 'TZ',
        name: 'Tanzania',
        cn: '坦桑尼亚',
        phone_code: '+255',
    },
    {
        code: 'TO',
        name: 'Tonga',
        cn: '汤加',
        phone_code: '+676',
    },
    {
        code: 'TC',
        name: 'Turks and Caicos Islands',
        cn: '特克斯和凯科斯群岛',
        phone_code: '+1649',
    },
    {
        code: 'TT',
        name: 'Trinidad and Tobago',
        cn: '特立尼达和多巴哥',
        phone_code: '+1868',
    },
    {
        code: 'TN',
        name: 'Tunisia',
        cn: '突尼斯',
        phone_code: '+216',
    },
    {
        code: 'TV',
        name: 'Tuvalu',
        cn: '图瓦卢',
        phone_code: '+688',
    },
    {
        code: 'TR',
        name: 'Turkey',
        cn: '土耳其',
        phone_code: '+90',
    },
    {
        code: 'TM',
        name: 'Turkmenistan',
        cn: '土库曼斯坦',
        phone_code: '+993',
    },
    {
        code: 'TK',
        name: 'Tokelau',
        cn: '托克劳',
        phone_code: '+690',
    },
    {
        code: 'WF',
        name: 'Wallis and Futuna',
        cn: '瓦利斯和富图纳',
        phone_code: '+681',
    },
    {
        code: 'VU',
        name: 'Vanuatu',
        cn: '瓦努阿图',
        phone_code: '+678',
    },
    {
        code: 'GT',
        name: 'Guatemala',
        cn: '危地马拉',
        phone_code: '+502',
    },
    {
        code: 'VE',
        name: 'Venezuela',
        cn: '委内瑞拉',
        phone_code: '+58',
    },
    {
        code: 'BN',
        name: 'Brunei',
        cn: '文莱',
        phone_code: '+673',
    },
    {
        code: 'UG',
        name: 'Uganda',
        cn: '乌干达',
        phone_code: '+256',
    },
    {
        code: 'UA',
        name: 'Ukraine',
        cn: '乌克兰',
        phone_code: '+380',
    },
    {
        code: 'UY',
        name: 'Uruguay',
        cn: '乌拉圭',
        phone_code: '+598',
    },
    {
        code: 'UZ',
        name: 'Uzbekistan',
        cn: '乌兹别克斯坦',
        phone_code: '+998',
    },
    {
        code: 'GR',
        name: 'Greece',
        cn: '希腊',
        phone_code: '+30',
    },
    {
        code: 'ES',
        name: 'Spain',
        cn: '西班牙',
        phone_code: '+34',
    },
    {
        code: 'EH',
        name: 'Western Sahara',
        cn: '西撒哈拉',
        phone_code: '+212',
    },
    {
        code: 'HK',
        name: 'Hong Kong',
        cn: '中国香港特别行政区',
        phone_code: '+852',
    },
    {
        code: 'SG',
        name: 'Singapore',
        cn: '新加坡',
        phone_code: '+65',
    },
    {
        code: 'NC',
        name: 'New Caledonia',
        cn: '新喀里多尼亚',
        phone_code: '+687',
    },
    {
        code: 'NZ',
        name: 'New Zealand',
        cn: '新西兰',
        phone_code: '+64',
    },
    {
        code: 'HU',
        name: 'Hungary',
        cn: '匈牙利',
        phone_code: '+36',
    },
    {
        code: 'SY',
        name: 'Syria',
        cn: '叙利亚',
        phone_code: '+963',
    },
    {
        code: 'JM',
        name: 'Jamaica',
        cn: '牙买加',
        phone_code: '+1876',
    },
    {
        code: 'AM',
        name: 'Armenia',
        cn: '亚美尼亚',
        phone_code: '+374',
    },
    {
        code: 'YE',
        name: 'Yemen',
        cn: '也门',
        phone_code: '+967',
    },
    {
        code: 'IQ',
        name: 'Iraq',
        cn: '伊拉克',
        phone_code: '+964',
    },
    {
        code: 'IR',
        name: 'Iran',
        cn: '伊朗',
        phone_code: '+98',
    },
    {
        code: 'IL',
        name: 'Israel',
        cn: '以色列',
        phone_code: '+972',
    },
    {
        code: 'IT',
        name: 'Italy',
        cn: '意大利',
        phone_code: '+39',
    },
    {
        code: 'IN',
        name: 'India',
        cn: '印度',
        phone_code: '+91',
    },
    {
        code: 'ID',
        name: 'Indonesia',
        cn: '印度尼西亚',
        phone_code: '+62',
    },
    {
        code: 'GB',
        name: 'United Kingdom',
        cn: '英国',
        phone_code: '+44',
    },
    {
        code: 'VG',
        name: 'British Virgin Islands',
        cn: '英属维京群岛',
        phone_code: '+1284',
    },
    {
        code: 'IO',
        name: 'British Indian Ocean Territory',
        cn: '英属印度洋领地',
        phone_code: '+246',
    },
    {
        code: 'JO',
        name: 'Jordan',
        cn: '约旦',
        phone_code: '+962',
    },
    {
        code: 'VN',
        name: 'Vietnam',
        cn: '越南',
        phone_code: '+84',
    },
    {
        code: 'ZM',
        name: 'Zambia',
        cn: '赞比亚',
        phone_code: '+260',
    },
    {
        code: 'JE',
        name: 'Jersey',
        cn: '泽西岛',
        phone_code: '+44',
    },
    {
        code: 'TD',
        name: 'Chad',
        cn: '乍得',
        phone_code: '+235',
    },
    {
        code: 'GI',
        name: 'Gibraltar',
        cn: '直布罗陀',
        phone_code: '+350',
    },
    {
        code: 'CL',
        name: 'Chile',
        cn: '智利',
        phone_code: '+56',
    },
    {
        code: 'CF',
        name: 'Central African Republic',
        cn: '中非共和国',
        phone_code: '+236',
    },
];
