const imgPath = 'images/sea_freight';
export const seaFreightList = [
    {
        label: 'Япония',
        flag: 'japan',
        map: imgPath,
        seoAlt: 'Япония',
    },
    {
        label: 'Малайзия',
        flag: 'malaysia',
        map: imgPath,
        seoAlt: 'Малайзия',
    },
    {
        label: 'Вьетнам',
        flag: 'vietnam',
        map: imgPath,
        seoAlt: 'Вьетнам',
    },
    {
        label: 'Турция',
        flag: 'turkey',
        map: imgPath,
        seoAlt: 'Турция',
    },
    {
        label: 'Европа',
        flag: 'eu',
        map: imgPath,
        seoAlt: 'Европа',
    },
    {
        label: 'Бразилия',
        flag: 'brazil',
        map: imgPath,
        seoAlt: 'Бразилия',
    },
    {
        label: 'Корея',
        flag: 'korea',
        map: imgPath,
        seoAlt: 'Корея',
    },
    {
        label: 'Тайвань',
        flag: 'taiwan',
        map: imgPath,
        seoAlt: 'Тайвань',
    },
    {
        label: 'Индия',
        flag: 'india',
        map: imgPath,
        seoAlt: 'Индия',
    },
    {
        label: 'Африка',
        flag: 'africa',
        map: imgPath,
        seoAlt: 'Африка',
    },
    {
        label: 'Чили',
        flag: 'chile',
        map: imgPath,
        seoAlt: 'Чили',
    },
    {
        label: 'Канада',
        flag: 'canada',
        map: imgPath,
        seoAlt: 'Канада',
    },
    {
        label: 'Китай',
        flag: 'china',
        map: imgPath,
        seoAlt: 'Китай',
    },
    {
        label: 'Индонезия',
        flag: 'indonesia',
        map: imgPath,
        seoAlt: 'Индонезия',
    },
    {
        label: 'Камбоджа',
        flag: 'cambodia',
        map: imgPath,
        seoAlt: 'Камбоджа',
    },
    {
        label: 'ОАЭ',
        flag: 'uae',
        map: imgPath,
        seoAlt: 'ОАЭ',
    },
    {
        label: 'США',
        flag: 'usa',
        map: imgPath,
        seoAlt: 'США',
    },
];
