export const texts = {
    homeHeader: 'Транспортно-экспедиторская компания',
    companyName: ' «Тис Лоджистик» ',
    homeSubheader:
        'Доставляем грузы «от двери к двери» из любой страны мира. <br>Основная деятельность — мультимодальные и ж/д перевозки в собственных контейнерах.',
    learnMore: 'Узнать подробнее',
    companyPhone: '8 (800) 234-80-70',
    companyEmail: 'info@tislogistic.ru',
    returnCall: 'Обратный звонок',
    calculateDelivery: 'Расчет доставки',
    about: 'О компании',
    services: 'Услуги',
    vacancies: 'Вакансии',
    contacts: 'Контакты',
    projects: 'Проекты',
    calculateTitle: 'Расчёт стоимости доставки',
    legalEntitiesOnly: 'Работаем только с юридическими лицами',
    step1: 'Шаг 1',
    step2: 'Шаг 2',
    from: 'Откуда',
    to: 'Куда',
    dest1: 'Москва',
    dest2: 'Санкт-Петербург',
    dest3: 'Новосибирск',
    dest4: 'Владивосток',
    dest5: 'Камчатка',
    dest6: 'Хабаровск',
    parcelDescription: 'Описание груза',
    calculatorNote:
        'Вы можете произвести расчёт, заполнив форму на сайте или же уточнить стоимость, проконсультировавшись с нашими менеджерами, заказав обратный звонок',
    next: 'Далее',
    back: 'Назад',
    send: 'Отправить',
    phone: 'Телефон',
    email: 'E-mail',
    calculatorEmailNote: 'Оставьте свой email, и мы пришлём вам расчёт',
    calculatorConfidentiality:
        'Нажимая кнопку <span class="bold">«Отправить»</span>, вы принимаете условия <span>пользовательского соглашения</span> и <span>политики конфиденциальности</span>',
    whyChooseUs: 'Почему стоит выбрать именно нас!',
    tonsPerYear: 'тонн, перевозим каждый год',
    tonsPerYearNumber: '3 100 000',
    contractsSigned: 'заключенных договоров',
    contractsSignedNumber: '13 500',
    experiencedEmployees: 'опытных сотрудников',
    experiencedEmployeesNumber: '1 400',
    warehouseArea: 'площадь терминально-складского комплекса',
    warehouseAreaNumber: '3 500 м2',
    branchesTitle: 'Представительства и филиалы в России',
    moscow: 'Москва',
    moscowPhone: '+7 495 646 72 10',
    moscowEmail: '020102@tislogistic.ru',
    spb: 'Санкт-Петербург',
    spbPhone: '+7 812 612 44 16',
    spbEmail: '080101@tislogistic.ru',
    khabarovsk: 'Хабаровск',
    khabarovskPhone: '+7 421 247 90 91',
    khabarovskEmail: '050101@tislogistic.ru',
    nakhodka: 'Находка',
    nakhodkaPhone: '+7 914 960-05-99',
    nakhodkaEmail: 'provvp@tislogistic.ru',
    vladivostok: 'Владивосток',
    vladivostokPhone: '8 800 234 80 70',
    vladivostokEmail: 'info@tislogistic.ru',
    novosibirsk: 'Новосибирск',
    novosibirskPhone: '+7 383 355 99 34',
    novosibirskEmail: 'bubnova@tislogistic.ru',
    ussuriysk: 'Уссурийск',
    ussuriyskPhone: '+7 423 431 95 95',
    ussuriyskEmail: 'ved@tislogistic.ru',
    partners: 'Партнеры',
    presentationTitle: 'Скачать презентацию компании',
    presentationDescription:
        'Перевозка опасных грузов — задача непростая. Нужно точно соблюсти все меры безопасности, предоставить сертификаты, промаркировать контейнеры.',
    download: 'Скачать',
    inkoterms: 'ИНКОТЕРМС 2020',
    containerClassification: 'Классификация контейнеров',
    vesselsPosition: 'Позиция и движение судов',
    tariffs: 'Тарифы на таможенное оформление грузов',
    websiteMap: 'Карта сайта',
    moscowAddress: '105093, ул. Золотая, 11, помещ. 10А21',
    vladivostokAddress: '690014, ул. Толстого, 32А, ТЦ «Велес», 2 этаж',
    confidentialityPolicy: 'Политика конфиденциальности',
    customerAgreement: 'Пользовательское соглашение',
    footerNote: '© 2022 Тис Лоджистик',
};
