export const texts = {
    homeHeader: 'Транспортно-экспедиторская компания',
    companyName: ' «Тис Лоджистик» ',
    homeSubheader:
        'Доставляем грузы «от двери к двери» из любой страны мира. <br>Основная деятельность — мультимодальные и ж/д перевозки в собственных контейнерах.',
    learnMore: 'Узнать подробнее',
    companyPhone: '8 (800) 234-80-70',
    companyEmail: 'info@tislogistic.ru',
    returnCall: 'Обратный звонок',
    calculateDelivery: 'Расчет доставки',
    about: 'О компании',
    services: 'Услуги',
    allServices: 'Все услуги',
    vacancies: 'Вакансии',
    contacts: 'Контакты',
    projects: 'Проекты',
    calculateTitle: 'Расчёт стоимости доставки',
    legalEntitiesOnly: 'Работаем только с юридическими лицами',
    step1: 'Шаг 1',
    step2: 'Шаг 2',
    from: 'Откуда',
    to: 'Куда',
    dest1: 'Москва',
    dest2: 'Санкт-Петербург',
    dest3: 'Новосибирск',
    dest4: 'Владивосток',
    dest5: 'Камчатка',
    dest6: 'Хабаровск',
    parcelDescription: 'Описание груза',
    calculatorNote:
        'Вы можете произвести расчёт, заполнив форму на сайте или же уточнить стоимость, проконсультировавшись с нашими менеджерами, заказав обратный звонок',
    next: 'Далее',
    back: 'Назад',
    send: 'Отправить',
    phone: 'Телефон',
    email: 'E-mail',
    calculatorEmailNote: 'Оставьте свой email, и мы пришлём вам расчёт',
    calculatorConfidentiality:
        'Нажимая кнопку <span class="bold">«Отправить»</span>, вы принимаете условия <span>пользовательского соглашения</span> и <span>политики конфиденциальности</span>',
    whyChooseUs: 'Почему стоит выбрать именно нас!',
    tonsPerYear: 'тонн, перевозим каждый год',
    tonsPerYearNumber: 3100000,
    contractsSigned: 'заключенных договоров',
    contractsSignedNumber: 13500,
    experiencedEmployees: 'опытных сотрудников',
    experiencedEmployeesNumber: 1400,
    warehouseArea: 'площадь терминально-складского комплекса',
    warehouseAreaNumber: 3500,
    warehouseAreaNumberSuffix: ' м2',
    branchesTitle: 'Представительства и филиалы в России',
    moscow: 'Москва',
    moscowPhone: '+7 495 646 72 10',
    moscowEmail: '020102@tislogistic.ru',
    spb: 'Санкт-Петербург',
    spbPhone: '+7 812 612 44 16',
    spbEmail: '080101@tislogistic.ru',
    khabarovsk: 'Хабаровск',
    khabarovskPhone: '+7 421 247 90 91',
    khabarovskEmail: '050101@tislogistic.ru',
    nakhodka: 'Находка',
    nakhodkaPhone: '+7 914 960-05-99',
    nakhodkaEmail: 'provvp@tislogistic.ru',
    vladivostok: 'Владивосток',
    vladivostokPhone: '8 800 234 80 70',
    vladivostokEmail: 'info@tislogistic.ru',
    novosibirsk: 'Новосибирск',
    novosibirskPhone: '+7 383 355 99 34',
    novosibirskEmail: 'bubnova@tislogistic.ru',
    ussuriysk: 'Уссурийск',
    ussuriyskPhone: '+7 423 431 95 95',
    ussuriyskEmail: 'ved@tislogistic.ru',
    partners: 'Партнеры',
    presentationTitle: 'Скачать презентацию компании',
    presentationDescription:
        'Перевозка опасных грузов — задача непростая. Нужно точно соблюсти все меры безопасности, предоставить сертификаты, промаркировать контейнеры.',
    download: 'Скачать',
    inkoterms: 'ИНКОТЕРМС 2020',
    containerClassification: 'Классификация контейнеров',
    vesselsPosition: 'Позиция и движение судов',
    tariffs: 'Тарифы на таможенное оформление грузов',
    websiteMap: 'Карта сайта',
    moscowAddress: '105093, ул. Золотая, 11, помещ. 10А21',
    vladivostokAddress: '690014, ул. Толстого, 32А, ТЦ «Велес», 2 этаж',
    confidentialityPolicy: 'Политика конфиденциальности',
    customerAgreement: 'Пользовательское соглашение',
    footerNote: '© 2022 Тис Лоджистик',
    companyProjects: 'Проекты компании:',
    allProjects: 'Все проекты',
    heavyEquipment: 'Тяжелое оборудование',
    heavyEquipmentDesc:
        'Перевозка негабаритного груза — всегда задача со звёздочкой.',
    projectsDate: '30 сентября 2022',
    toxicPaint: 'Опасная краска',
    toxicPaintDesc:
        'Перевозка опасных грузов — задача непростая. Нужно точно соблюсти все меры безопасности, предоставить сертификаты, промаркировать контейнеры.',
    lamborginiJapan:
        'Ламборгини из Японии, или сложности доставки в условиях санкций',
    lamborginiJapanDesc:
        'Как доставить груз, когда, а отправитель отказывается отправлять его в Россию?',
    safelyTransport: 'Надежно перевезём ваш груз в собственных контейнерах',
    importFromCountries: 'Импорт из стран Азии, Европы и Америки',
    details: 'Подробнее',
    ownContainers: 'Собственный контейнерный парк',
    ownContainersDesc: 'Более 3000 единиц для мультимодальных перевозок',
    storageComplex: 'Терминально-складской комплекс',
    storageComplexDesc:
        '3 500 м² помещений для приёма и распределения грузов на холодном и теплом складе с эффективной организацией',
    qualifiedEmployees: 'Квалифицированный персонал',
    qualifiedEmployeesDesc: 'Более 170 опытных профессионалов',
    presenceGeography: 'География присутствия',
    presenceGeographyDesc: '7 филиалов и 20 представительств',
    seaFreight: 'Морские грузоперевозки',
    trainFreight: 'Железнодорожные грузоперевозки ',
    carFreight: 'Автомобильные  перевозки',
    airFreight: 'Авиаперевозки',
    oversizedCargo: 'Перевозка генеральных и негабаритных грузов',
    customsDeclarations: 'Таможенное оформление',
    storage: 'Ответственное хранение',
    cargoForwarding: 'Экспедирование грузов',
    companyValues: 'Ценности компании',
    ourMission: 'Наша миссия –',
    ourMissionDesc:
        'обеспечить процесс логистики максимально удобным для наших клиентов, предоставив комфортные условия для роста и развития их бизнеса.',
    professionalism: 'Профессионализм — ',
    professionalismDesc:
        'мы стремимся делать больше и лучше, постоянно наращивая наш опыт и компетенции в области транспортной логистики, а также уделяем особое внимание качеству нашей работы.',
    improvement: 'Постоянное совершенствование — ',
    improvementDesc:
        'мы ориентированы как на эффективность и прибыльность компании, так и на личностное совершенствование каждого сотрудника, создавая комфортные условия для работы.',
    ecologyCompliance: 'Экологичность — ',
    ecologyComplianceDesc:
        'мы заботимся об экологии и поддерживаем экологические инициативы, предоставляя чистые решения в нашей деятельности.',
    useUs: 'Воспользовавшись услугами нашей транспортной компании, вы сможете отправить и получить международные (мультимодальные) грузы из любой страны мира в любой город России «под ключ». ',
    backToForm: 'Вернуться к форме расчета',
};
