import { texts } from './../../config/texts';
const imgPath = 'images/containers/';

export const containers = [
    {
        title: "40-ка футовый контейнер Pallet Wide \n(40' НC PW, увеличенной вместимости)",
        description:
            'Это новый тип контейнеров увеличенной вместимости в международной практике, которые вмещают 30 евро-паллет по полу. Подобная вместимость обеспечивается за счёт увеличенной ширины контейнера (сокращение глубины рёбер).',
        outer: {
            length: '12192',
            width: '2484',
            height: '2896',
        },
        inner: {
            length: '12100',
            width: '2426',
            height: '2694',
        },
        doors: {
            width: '2360',
            height: '2585',
        },
        maxGrossWeight: '34000 kg',
        tare: '4150 kg',
        maxLoad: '29850 kg',
        volume: '79.1 cub. M>',
        img: imgPath + 'container1.png',
    },
    {
        title: "20-ти футовый контейнер Pallet Wide \n(20' НC PW, увеличенной вместимости)",
        description:
            'Используется при транспортировке небольших негабаритных грузов или среднего количества мелких негабаритных грузов',
        outer: {
            length: '6058',
            width: '2484',
            height: '2896',
        },
        inner: {
            length: '5898',
            width: '2440',
            height: '2698',
        },
        doors: {
            width: '2374',
            height: '2585',
        },
        maxGrossWeight: '30480 kg',
        tare: '2560 kg',
        maxLoad: '27920 kg',
        volume: '38.4 cub. M>',
        img: imgPath + 'container2.png',
        className: 'shrink-img',
    },
    {
        title: '20-футовый контейнер усиленный \n(HEAVY TESTED)',
        description:
            'Для перевозки тяжелых грузов (керамогранит, природный камень, металлические изделия)',
        outer: {
            length: '6058',
            width: '2438',
            height: '2591',
        },
        inner: {
            length: '5898',
            width: '2352',
            height: '2393',
        },
        doors: {
            width: '234',
            height: '228',
        },
        maxGrossWeight: '2300 kg',
        tare: '',
        maxLoad: '28200 kg',
        volume: '33.10 cub. M>',
        img: imgPath + 'container2.png',
        className: 'shrink-img',
    },
    {
        title: '45-ти футовый стандартный контейнер',
        description:
            '45-ти футовый стандартный контейнер используется для перевозки легких и объемных грузов, а также идеально подходит для перевозки грузов длиной ровно 12 метров и более до 13,5 метров.',
        outer: {
            length: '13742',
            width: '2438',
            height: '2895',
        },
        inner: {
            length: '13582',
            width: '2347',
            height: '2690',
        },
        doors: {
            width: '2340',
            height: '2584',
        },
        maxGrossWeight: '32500 kg',
        tare: '4110 kg',
        maxLoad: '28390 kg',
        volume: '85.7 cub. M>',
        img: imgPath + 'container4.png',
    },
    {
        title: "40-ка футовый High Cube (40' НC) контейнер \n(увеличенной вместимости)",
        description: texts.containerSharedDescription,
        outer: {
            length: '12192',
            width: '2438',
            height: '2896',
        },
        inner: {
            length: '12032',
            width: '2352',
            height: '2698',
        },
        doors: {
            width: '2340',
            height: '2585',
        },
        maxGrossWeight: '32500 kg',
        tare: '3850 kg',
        maxLoad: '28650 kg',
        volume: '76.4 cub. M>',
        img: imgPath + 'container1.png',
    },
    {
        title: "20-ти футовый High Cube (20' НC) контейнер \n(увеличенной вместимости)",
        description: texts.containerSharedDescription,
        outer: {
            length: '6058',
            width: '2484',
            height: '2896',
        },
        inner: {
            length: '5898',
            width: '2440',
            height: '2698',
        },
        doors: {
            width: '2374',
            height: '2585',
        },
        maxGrossWeight: '30480 kg',
        tare: '2560 kg',
        maxLoad: '27920 kg',
        volume: '38.4 cub. M>',
        img: imgPath + 'container2.png',
        className: 'shrink-img',
    },
    {
        title: '40-ка футовый стандартный (стальной) контейнер',
        description: texts.containerSharedDescription2,
        outer: {
            length: '12192',
            width: '2438',
            height: '2591',
        },
        inner: {
            length: '12039',
            width: '2350',
            height: '2372mm',
        },
        doors: {
            width: '2336',
            height: '2291',
        },
        maxGrossWeight: '30480 kg',
        tare: '3980 kg',
        maxLoad: '26500 kg',
        volume: '66.5 cub. M>',
        img: imgPath + 'container4.png',
    },
    {
        title: '20-ти футовый стандартный (стальной) контейнер',
        description: texts.containerSharedDescription2,
        outer: {
            length: '6058',
            width: '2438',
            height: '2591',
        },
        inner: {
            length: '5898',
            width: '2352',
            height: '2393',
        },
        doors: {
            width: '2340',
            height: '2280',
        },
        maxGrossWeight: '30480 kg',
        tare: '2220 kg',
        maxLoad: '28260 kg',
        volume: '33.2 cub. M>',
        img: imgPath + 'container2.png',
        className: 'shrink-img',
    },
    {
        title: '20-ти футовый  (стальной) контейнер \nOPEN TOP с открытым верхом',
        description: texts.containerSharedDescription3,
        outer: {
            length: '6096',
            width: '2438',
            height: '2591',
        },
        inner: {
            length: '5902',
            width: '2240',
            height: '2352',
        },
        doors: {
            width: '2335',
            height: '2240',
        },
        maxGrossWeight: '24000 kg',
        tare: '2440 kg',
        maxLoad: '21560 kg',
        volume: '32 cub. M>',
        img: imgPath + 'container9.png',
        className: 'shrink-img-open',
    },
    {
        title: '40-футовый (стальной) контейнер \nс открытым верхом',
        description: texts.containerSharedDescription3,
        outer: {
            length: '6096',
            width: '2438',
            height: '2591',
        },
        inner: {
            length: '5902',
            width: '2240',
            height: '2352',
        },
        doors: {
            width: '2335',
            height: '2240',
        },
        maxGrossWeight: '24000 kg',
        tare: '2440 kg',
        maxLoad: '21560 kg',
        volume: '32 cub. M>',
        img: imgPath + 'container10.png',
        className: 'grow-img',
    },
    {
        title: '40-футовый (стальной) контейнер Hard Top \ncо снимаемой жесткой крышкой',
        description:
            'Для удобства погрузки контейнер оборудуют съемной верхней перекладиной над дверями в торце контейнера.',
        outer: {
            length: '12192',
            width: '2438',
            height: '2591',
        },
        inner: {
            length: '12021',
            width: '2350',
            height: '2330',
        },
        doors: {
            width: '2338',
            height: '2234',
        },
        maxGrossWeight: '36000 kg',
        tare: '4430 kg',
        maxLoad: '31570 kg',
        volume: '66.7 cub. M>',
        img: imgPath + 'container11.png',
        className: 'grow-img',
    },
    {
        title: '20-ти футовый  (стальной) контейнер \nс торцевыми стенками',
        description: texts.containerSharedDescription4,
        outer: {
            length: '6096',
            width: '2438',
            height: '2591',
        },
        inner: {
            length: '5737',
            width: '2240',
            height: '2170 mm\n420 mm\n(компактный)',
        },
        doors: {
            width: '--',
            height: '--',
        },
        maxGrossWeight: '30480 kg',
        tare: '2950 kg',
        maxLoad: '27530 kg',
        volume: '27.9 cub. M>',
        img: imgPath + 'container12.png',
        className: 'grow-img stretch-row',
    },
    {
        title: '40-ка футовый  (стальной) контейнер \nс торцевыми стенками',
        description: texts.containerSharedDescription4,
        outer: {
            length: '12192',
            width: '2438',
            height: '2591',
        },
        inner: {
            length: '12032',
            width: '2240',
            height: '2034 mm\n570 mm\n(компактный)',
        },
        doors: {
            width: '--',
            height: '--',
        },
        maxGrossWeight: '45000 kg',
        tare: '5530 kg',
        maxLoad: '39470 kg',
        volume: '58.8 cub. M>',
        img: imgPath + 'container13.png',
        className: 'grow-img stretch-row',
    },
    {
        title: '40-ка футовый High Cube рефрижераторный (стальной) контейнер (увеличенной вместимости)',
        description: texts.containerSharedDescription,
        outer: {
            length: '12192',
            width: '2438',
            height: '2895',
        },
        inner: {
            length: '11560',
            width: '2286',
            height: '2500',
        },
        doors: {
            width: '2286',
            height: '2478',
        },
        maxGrossWeight: '30480 kg',
        tare: '4200 kg',
        maxLoad: '26280 kg',
        volume: '66.1 cub. M>',
        img: imgPath + 'container1.png',
    },
    {
        title: '40-ка футовый рефрижераторный \n(стальной) контейнер',
        description: texts.containerSharedDescription,
        outer: {
            length: '12192',
            width: '2438',
            height: '2591',
        },
        inner: {
            length: '11555',
            width: '2286',
            height: '2280',
        },
        doors: {
            width: '2286',
            height: '2245',
        },
        maxGrossWeight: '30480 kg',
        tare: '4370 kg',
        maxLoad: '26110 kg',
        volume: '60.2 cub. M>',
        img: imgPath + 'container4.png',
    },
    {
        title: '20-ти футовый рефрижераторный \n(стальной) контейнер',
        description: texts.containerSharedDescription,
        outer: {
            length: '6096',
            width: '2370',
            height: '2591',
        },
        inner: {
            length: '5455',
            width: '2260',
            height: '2275',
        },
        doors: {
            width: '72237',
            height: '2260',
        },
        maxGrossWeight: '27000 kg',
        tare: '3050 kg',
        maxLoad: '23950 kg',
        volume: '28.0 cub. M>',
        img: imgPath + 'container2.png',
        className: 'shrink-img',
    },
];
export const containersRus = {
    sizesDesignation: {
        3: '3 т',
        5: '5 т',
        20: '20 т',
        24: '24 т',
    },
    grossWeightTonns: {
        3: '3,0',
        5: '5,0',
        20: '20,0',
        24: '24,0',
    },
    innerVolume: {
        3: '5,16',
        5: '10,40',
        20: '30,60',
        24: '32,70',
    },
    sizes: {
        outer: {
            length: {
                3: 2100,
                5: 2650,
                20: 6058,
                24: 6058,
            },
            width: {
                3: 1325,
                5: 2100,
                20: 2438,
                24: 2438,
            },
            height: {
                3: 2400,
                5: 2400,
                20: 2438,
                24: 2591,
            },
        },
        inner: {
            length: {
                3: 1930,
                5: 2515,
                20: 5867,
                24: 5867,
            },
            width: {
                3: 1225,
                5: 1950,
                20: 2330,
                24: 2330,
            },
            height: {
                3: 2128,
                5: 2128,
                20: 2197,
                24: 2350,
            },
        },
        doors: {
            width: {
                3: 1225,
                5: 1950,
                20: 2286,
                24: 2286,
            },
            height: {
                3: 2090,
                5: 2100,
                20: 2134,
                24: 2261,
            },
        },
    },
};
